import Link from "next/link";
import { ArrowRight, BarChart3, Check, Clock3, FileText, Link2, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { PublicNav } from "@/components/PublicNav";

const features = [
  [FileText, "Invoice in minutes", "Line items, tax, discounts, dates and totals calculate as you type."],
  [Link2, "Share one clean link", "Clients can open, review and pay an invoice without creating an account."],
  [BarChart3, "Know your cash position", "See earned, outstanding and overdue amounts at a glance."],
];

export default function HomePage() {
  return <main className="min-h-screen overflow-hidden bg-white">
    <div className="absolute inset-x-0 top-0 -z-10 h-[680px] bg-[radial-gradient(circle_at_30%_15%,rgba(99,102,241,.16),transparent_36%),radial-gradient(circle_at_80%_0%,rgba(14,165,233,.10),transparent_30%)]" />
    <PublicNav />
    <section className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 pt-16 sm:px-8 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:pt-24">
      <div>
        <div className="inline-flex items-center gap-2 rounded-full border border-brand-100 bg-brand-50 px-3 py-1.5 text-xs font-bold text-brand-700"><Sparkles size={13}/> Built for freelancers & small studios</div>
        <h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.03] tracking-[-0.04em] text-ink sm:text-6xl">Invoices that look <span className="text-brand-600">professional</span> and get paid.</h1>
        <p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">BillFlow replaces messy spreadsheets with a focused invoicing workspace for creating, sending, sharing and tracking every invoice.</p>
        <div className="mt-8 flex flex-wrap items-center gap-3"><Link href="/signup" className="inline-flex items-center gap-2 rounded-xl bg-ink px-5 py-3 text-sm font-bold text-white shadow-lg shadow-slate-300/30 hover:bg-slate-800">Start for free <ArrowRight size={16}/></Link><a href="#features" className="rounded-xl px-5 py-3 text-sm font-bold text-slate-700 hover:bg-slate-100">See how it works</a></div>
        <div className="mt-8 flex flex-wrap gap-5 text-sm text-slate-500"><span className="inline-flex items-center gap-2"><Check size={16} className="text-emerald-600"/> No credit card</span><span className="inline-flex items-center gap-2"><ShieldCheck size={16} className="text-emerald-600"/> Passwords hashed</span><span className="inline-flex items-center gap-2"><Zap size={16} className="text-emerald-600"/> Fast setup</span></div>
      </div>
      <div className="relative animate-float"><div className="absolute -inset-8 rounded-[2.5rem] bg-brand-100/50 blur-3xl"/><div className="relative overflow-hidden rounded-[2rem] border border-slate-200 bg-white p-5 shadow-soft sm:p-7"><div className="flex items-center justify-between border-b border-line pb-5"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-slate-400">Invoice</p><p className="mt-1 text-2xl font-black">NST-1002</p></div><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-700">Sent</span></div><div className="grid grid-cols-2 gap-5 py-6 text-sm"><div><p className="text-slate-400">From</p><p className="mt-1 font-bold">Northstar Studio</p></div><div><p className="text-slate-400">Bill to</p><p className="mt-1 font-bold">Vertex Labs</p></div></div><div className="space-y-3 border-t border-line pt-5"><div className="flex justify-between text-sm"><span className="text-slate-600">Website development sprint</span><b>₹54,000</b></div><div className="flex justify-between text-sm"><span className="text-slate-600">Deployment & QA</span><b>₹9,000</b></div></div><div className="mt-5 rounded-2xl bg-slate-50 p-4"><div className="flex justify-between text-sm"><span className="text-slate-500">Subtotal</span><span>₹63,000</span></div><div className="mt-2 flex justify-between text-sm"><span className="text-slate-500">GST</span><span>₹11,340</span></div><div className="mt-4 flex justify-between border-t border-line pt-4"><span className="font-bold">Total</span><span className="text-xl font-black">₹74,340</span></div></div><div className="mt-5 flex gap-2"><span className="flex-1 rounded-xl bg-ink py-3 text-center text-sm font-bold text-white">Pay invoice</span><span className="rounded-xl border border-line px-4 py-3 text-sm font-bold">PDF</span></div></div></div>
    </section>
    <section id="features" className="border-y border-slate-200 bg-slate-50/70"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.14em] text-brand-600">Everything essential</p><h2 className="mt-3 text-3xl font-black tracking-tight text-ink sm:text-4xl">A small product that handles the big invoicing moments.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(([Icon, title, text]) => { const I = Icon as any; return <div key={title as string} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-panel"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-brand-50 text-brand-600"><I size={21}/></div><h3 className="mt-5 text-lg font-black">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text as string}</p></div> })}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 text-center sm:px-8"><Clock3 size={24} className="mx-auto text-brand-600"/><h2 className="mt-4 text-3xl font-black tracking-tight">Stop chasing spreadsheets.</h2><p className="mx-auto mt-3 max-w-xl text-slate-500">Build the invoice, share the link, see when it gets paid. BillFlow keeps the workflow compact and clear.</p><Link href="/signup" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-ink px-5 py-3 text-sm font-bold text-white">Create your workspace <ArrowRight size={16}/></Link></section>
    <footer className="border-t border-slate-200 py-8 text-center text-xs text-slate-400">© {new Date().getFullYear()} BillFlow. Crafted for independent teams.</footer>
  </main>
}
