function pdfText(value: unknown) {
  return String(value ?? "")
    .normalize("NFKD")
    .replace(/[^\x20-\x7E]/g, "?")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function moneyText(value: number, currency: string) {
  return `${currency} ${value.toFixed(2)}`;
}

type PdfInvoice = {
  number: string;
  issueDate: Date;
  dueDate: Date;
  notes?: string | null;
  taxRate: unknown;
  discountRate: unknown;
  client: { name: string; company?: string | null; email: string; address?: string | null };
  business: { name: string; currency: string };
  lineItems: { description: string; quantity: unknown; rate: unknown }[];
  totals: { subtotal: number; discount: number; tax: number; total: number };
  status: string;
};

function dateText(date: Date) {
  return new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }).format(date);
}

/** Small dependency-free PDF writer for invoice downloads. */
export function buildInvoicePdf(invoice: PdfInvoice) {
  const lines: string[] = [];
  const add = (x: number, y: number, size: number, text: string, bold = false) => {
    lines.push(`BT /${bold ? "F2" : "F1"} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${pdfText(text)}) Tj ET`);
  };
  add(54, 752, 20, invoice.business.name, true);
  add(54, 728, 10, `Invoice ${invoice.number}`, true);
  add(54, 710, 9, `Issue: ${dateText(invoice.issueDate)}   Due: ${dateText(invoice.dueDate)}   Status: ${invoice.status}`);
  add(54, 678, 10, "Bill to", true);
  add(54, 662, 10, invoice.client.name, true);
  if (invoice.client.company) add(54, 646, 9, invoice.client.company);
  add(54, 632, 9, invoice.client.email);
  if (invoice.client.address) add(54, 616, 9, invoice.client.address.replace(/\r?\n/g, " | "));

  add(54, 578, 9, "DESCRIPTION", true);
  add(360, 578, 9, "QTY", true);
  add(410, 578, 9, "RATE", true);
  add(500, 578, 9, "AMOUNT", true);

  let y = 556;
  for (const item of invoice.lineItems) {
    if (y < 145) break;
    const qty = Number(item.quantity);
    const rate = Number(item.rate);
    add(54, y, 9, item.description.slice(0, 52));
    add(360, y, 9, String(qty));
    add(410, y, 9, moneyText(rate, invoice.business.currency));
    add(500, y, 9, moneyText(qty * rate, invoice.business.currency));
    y -= 22;
  }

  y -= 12;
  add(390, y, 9, "Subtotal", true);
  add(500, y, 9, moneyText(invoice.totals.subtotal, invoice.business.currency));
  y -= 18;
  add(390, y, 9, `Discount (${Number(invoice.discountRate).toFixed(2)}%)`);
  add(500, y, 9, `-${moneyText(invoice.totals.discount, invoice.business.currency)}`);
  y -= 18;
  add(390, y, 9, `Tax (${Number(invoice.taxRate).toFixed(2)}%)`);
  add(500, y, 9, moneyText(invoice.totals.tax, invoice.business.currency));
  y -= 24;
  add(390, y, 12, "Total", true);
  add(500, y, 12, moneyText(invoice.totals.total, invoice.business.currency), true);
  if (invoice.notes) {
    y -= 42;
    add(54, y, 9, "Notes", true);
    y -= 16;
    for (const noteLine of invoice.notes.split(/\r?\n/).slice(0, 5)) {
      add(54, y, 9, noteLine.slice(0, 110));
      y -= 14;
    }
  }
  add(54, 48, 8, "Generated by BillFlow");

  const content = `q\n${lines.join("\n")}\nQ`;
  const objects: string[] = [];
  const addObject = (body: string) => { objects.push(body); return objects.length; };
  addObject("<< /Type /Catalog /Pages 2 0 R >>");
  addObject("<< /Type /Pages /Kids [3 0 R] /Count 1 >>");
  addObject("<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>");
  addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
  addObject(`<< /Length ${Buffer.byteLength(content, "ascii")} >>\nstream\n${content}\nendstream`);

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((body, index) => {
    offsets[index + 1] = Buffer.byteLength(pdf, "binary");
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xref = Buffer.byteLength(pdf, "binary");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let i = 1; i <= objects.length; i++) pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return Buffer.from(pdf, "binary");
}
