export const SUBSCRIPTION_PLANS = {
  STARTER: {
    id: "STARTER",
    name: "Starter",
    price: 9,
    priceYearly: 7,
    interval: "month",
    invoicesLimit: 30,
    hasGstSupport: false,
    tagline: "Essential billing tools for freelancers and independent solo founders.",
    badge: "Solo",
    features: [
      "Up to 30 active invoices/month",
      "Unlimited clients & contacts",
      "Executive PDF generation & downloads",
      "Branded public invoice payment portal",
      "Multi-currency support (USD, EUR, GBP, INR, etc.)",
      "Automated standard tax & discount calculations",
      "Custom invoice prefix & numbering",
      "Standard email support",
    ],
  },
  PRO: {
    id: "PRO",
    name: "Pro Studio",
    price: 15,
    priceYearly: 12,
    interval: "month",
    invoicesLimit: -1, // Unlimited
    hasGstSupport: false,
    tagline: "Everything you need to run invoicing for expanding design & engineering studios.",
    badge: "Most Popular",
    features: [
      "Unlimited invoices & line items",
      "Unlimited clients & contacts",
      "Executive PDF invoices with bank callout & status stamps",
      "Automated overdue tracking & payment alerts",
      "Cash flow & revenue analytics dashboard",
      "One-click CSV & financial report export",
      "Custom invoice numbering & business sequence control",
      "Priority 24/7 dedicated support & SLA",
      "Early access to automated retainers & live webhooks",
    ],
  },
  ORGANIZATION: {
    id: "ORGANIZATION",
    name: "Organization GST",
    price: 29,
    priceYearly: 24,
    interval: "month",
    invoicesLimit: -1, // Unlimited
    hasGstSupport: true,
    tagline: "Complete legal compliance & GST Tax Invoicing for registered companies & agencies.",
    badge: "Enterprise Ready",
    features: [
      "Full Indian GST Compliance (Intra vs Inter-State automation)",
      "Automatic CGST (9%) + SGST (9%) or IGST (18%) tax splitting",
      "Place of Supply resolution & 36 State Code tracking",
      "Legal TAX INVOICE format with HSN / SAC codes on line items",
      "Verified Seller & Client GSTIN / PAN display on invoices & PDFs",
      "Bank Account details (A/C, IFSC, UPI ID & QR) on invoices",
      "GSTR-1 compliant ledger breakdown & summary exports",
      "Unlimited invoices, clients, and multi-user access",
      "VIP Dedicated Account Manager & 99.9% Uptime SLA",
    ],
  },
} as const;

export type PlanKey = keyof typeof SUBSCRIPTION_PLANS;
